version: '3.2'

services:
    blog:
        container_name: vallheru_blog
        build:
            context: ./
            dockerfile: ./blog/Dockerfile
            args:
                HUGO_BASE_URL: ${BLOG_BASE_URL}
        ports:
             - "8383:1313"
        environment:
            HUGO_BASE_URL: ${BLOG_URL}
            HUGO_PAGE_NAME: ${BLOG_NAME}
        volumes:
            - ./blog_src:/app/blog

    thelongue:
        container_name: vallheru_thelongue
        image: thelounge/lounge:latest
        volumes:
            - ./thelongue:/home/lounge/data
        privileged: true
        ports:
            - "8183:9000"
        networks:
            apps_network:
                aliases:
                    - thelongue
                ipv4_address: 172.16.222.13

    vault:
         container_name: vallheru_vault
         image: vault:1.1.0
         privileged: true
         volumes:
             - ./vault/config.hcl:/vault/config/config.hcl
             - ./wait-for.sh:/wait-for-it.sh
         command:
             - "/wait-for-it.sh"
             - "mysql:3306"
             - "--timeout=15"
             - "--"
             - "vault"
             - "server"
             - "-config=/vault/config/config.hcl"
         networks:
             apps_network:
                 aliases:
                     - vault
                 ipv4_address: 172.16.222.11

    pgsql:
        container_name: vallheru_pgsql
        image: postgres:11
        restart: always
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
            POSTGRES_USER: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./pgsql:/var/lib/postgresql/data
        networks:
            apps_network:
                aliases:
                    - pgsql
                    - postgresql
                ipv4_address: 172.16.222.16


    mysql:
        container_name: vallheru_mysql
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf.d/custom.conf:/etc/mysql/conf.d/z-custom.conf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            apps_network:
                aliases:
                    - mysql
                    - db
                ipv4_address: 172.16.222.10


    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        ports:
            - "8180:8080"
        networks:
            apps_network:
                aliases:
                    - adminer
                ipv4_address: 172.16.222.9


    nextcloud:
        image: nextcloud
        restart: always
        labels:
            app.name: "vallheru_nextcloud"
        environment:
            UTF8MB4_ENABLED: 0
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: root
            MYSQL_HOST: mysql
            NEXTCLOUD_TABLE_PREFIX: nc_
            NEXT_CLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
            NEXT_CLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}

        ports:
            - "8181:80"
        volumes:
            - ./nextcloud/nextcloud:/var/www/html
            - ./nextcloud/apps:/var/www/html/custom_apps
            - ./nextcloud/config:/var/www/html/config
            - ./nextcloud/data:/var/www/html/data
        depends_on:
            - mysql
        networks:
            apps_network:
                aliases:
                    - nextcloud
                ipv4_address: 172.16.222.12

networks:
    apps_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.222.0/24
